### ISSUE TITLE
Separate out Eslint and Browserslist configs

### ISSUE THREAD

**Issue by gregjopa** [krakenjs/grumbler-scripts#5]
Both Eslint and Browserslist support creating shared configs as modules. It would be great to pull these out of grumbler-scripts to make them easier to share.

Something like:
```
npm install @paypal/eslint-config-paypal-checkout
npm install @paypal/browserslist-config-paypal-checkout
```

https://github.com/browserslist/browserslist#shareable-configs
https://eslint.org/docs/developer-guide/shareable-configs

**Comment by westeezy** [comment]
After released v5 and some recent developers in eslint I think we should revisit this. cc @crookedneighbor

**Comment by gregjopa** [comment]
This feature request is complete. grumbler-scripts is now a monorepo with the following packages:

- [@krakenjs/babel-config-grumbler](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/babel-config-grumbler/README.md)
- [@krakenjs/eslint-config-grumbler](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/eslint-config-grumbler/README.md)
- [@krakenjs/grumbler-scripts](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/grumbler-scripts/README.md)
- [@krakenjs/karma-config-grumbler](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/karma-config-grumbler/README.md)
- [@krakenjs/typescript-config-grumbler](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/typescript-config-grumbler/README.md)
- [@krakenjs/webpack-config-grumbler](https://github.com/krakenjs/grumbler-scripts/blob/main/packages/webpack-config-grumbler/README.md)

Awesome work @westeezy! 💯
