### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [krakenjs/grumbler-scripts#6]
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by gruiz90** [comment]
Hi @mstuart , I would like to learn a bit more about TypeScript, could you assign me this one?

**Comment by mstuart** [comment]
@gruiz90 Ok, done! Happy hacking!

**Comment by gruiz90** [comment]
@mstuart Here is the PR created to DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48555

One thing I noticed just now is that on the package.json the repository referenced is krakenjs/grumbler git repo. The same on npm having the repo not as grumbler-scripts.

**Comment by mstuart** [comment]
Thanks @gruiz90! Usually the contributors are quick to jump on DefinitelyTyped PRs. Maybe they have an overwhelming amount w/ hacktoberfest. Once it's merged on DefinitelyTyped, will mark you down for those PayPal socks and ping you later to collect shipping info. Thanks!

Ah, I didn't notice the URL was incorrect. Thanks for letting me know!

**Comment by gruiz90** [comment]
Sounds good! I'll let you know when I have news about the PR.

**Comment by orta** [comment]
Yep, there's a _lot_ of PRs on DT right now. That's been accepted, you should see it in `@types` in a few hours.

**Comment by gruiz90** [comment]
Hey @mstuart! I installed the @types/grumbler-scripts package today to verify it and it's getting all the types ok for the respective modules! That should be all for the issue right?

**Comment by mstuart** [comment]
@gruiz90 Sweet! Yep, that's it :D

**Comment by gregjopa** [comment]
I'm going to close this one out. This project now supports TypeScript.
